# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="markdown-include"
REALVERSION="0.5.1"
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,2_7,3_3,3_4,3_5,3_3,3_4} )

inherit gs-pypi

DESCRIPTION="This is an extension to Python-Markdown which provides an include function, similar to that found in LaTeX (and also the C pre-processor and Fortran). I originally wrote it for my FORD Fortran auto-documentation generator."

HOMEPAGE="https://github.com/cmacmackin/markdown-include/"
LICENSE="GPL-3"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="dev-python/markdown"

RDEPEND="${DEPEND}"
