# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="toposort"
REALVERSION="1.4"
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,3_3,3_4} )

inherit gs-pypi

DESCRIPTION="Implements a topological sort algorithm."

HOMEPAGE="https://bitbucket.org/ericvsmith/toposort"
LICENSE="Apache-2.0"

SLOT="0"
KEYWORDS="~amd64 ~x86"

